export type Product = {
  slug: string;
  name: string;
  tagline: string;
  description: string;
  category: string;
  icon: string;
  monthlyPrice: number;
  features: string[];
  featured?: boolean;
  comingSoon?: boolean;
};

// Catalogue de produits SaaS (produits phares en tête)
export const products: Product[] = [
  {
    slug: "versailles",
    name: "Versailles",
    tagline: "Le chef qui rend tous vos sites incontournables sur Google et les IA",
    description:
      "Versailles se connecte à l'ensemble de vos sites web et comptes (avec votre autorisation) et les pilote en SEO, GEO et AEO pour vous rendre influent partout : Google, mais aussi ChatGPT, Perplexity, Gemini et les AI Overviews. Il exécute comme un soldat, cherche 24h/24 de nouveaux mots-clés et de nouveaux moteurs, et s'adapte en continu. Il préside aussi vos réunions d'équipe IA : il cadre, écoute, tranche et lance les actions.",
    category: "Intelligence",
    icon: "👑",
    monthlyPrice: 299,
    features: [
      "Connexion à tous vos sites & comptes (accès autorisé)",
      "SEO multi-sites (Google & moteurs classiques)",
      "GEO — optimisation pour les moteurs génératifs (ChatGPT, Perplexity, Gemini, AI Overviews)",
      "AEO — optimisation pour les moteurs de réponse",
      "Veille 24h/24 de nouveaux mots-clés et de nouveaux moteurs",
      "Exécution autonome multi-sites (« comme un soldat »)",
      "Architecture évolutive",
      "Chef des réunions d'équipe IA",
      "Validation des actions sensibles & rapport d'exécution",
    ],
    featured: true,
  },
  {
    slug: "ai-company",
    name: "AI Company",
    tagline: "D'une idée à une entreprise complète, automatiquement",
    description:
      "Transformez une simple idée en entreprise entière. L'IA crée et orchestre tout : site web, application, comptabilité, publicités, support client, ventes, recrutement et rapports. Pensé pour chaque nouvel entrepreneur.",
    category: "Intelligence",
    icon: "🚀",
    monthlyPrice: 199,
    features: [
      "Site web généré",
      "Application sur mesure",
      "Comptabilité automatisée",
      "Campagnes publicitaires",
      "Support client",
      "Ventes & prospection",
      "Recrutement",
      "Rapports & pilotage",
    ],
    featured: true,
  },
  {
    slug: "internet-brain",
    name: "Internet Brain",
    tagline: "L'IA qui surveille Internet pour vous, 24h/24",
    description:
      "Une intelligence artificielle qui veille en continu sur le web et détecte pour vous : nouveaux business, concurrents, tendances, fournisseurs, investisseurs et clients. Puis elle propose directement les actions à mener.",
    category: "Intelligence",
    icon: "🧠",
    monthlyPrice: 99,
    features: [
      "Veille du web 24h/24",
      "Détection de nouveaux business & tendances",
      "Surveillance des concurrents",
      "Repérage de fournisseurs, investisseurs & clients",
      "Recommandations d'actions concrètes",
      "Alertes en temps réel",
    ],
    featured: true,
  },
  {
    slug: "billion-dollar-scanner",
    name: "Billion Dollar Scanner",
    tagline: "Détectez les opportunités à un milliard avant tout le monde",
    description:
      "Un scanner qui analyse des millions de données publiques pour faire émerger les meilleures opportunités : entreprises à vendre, noms de domaine oubliés, produits en pleine explosion, mots-clés rentables et niches sans concurrence.",
    category: "Intelligence",
    icon: "💰",
    monthlyPrice: 129,
    features: [
      "Analyse de millions de données publiques",
      "Entreprises à vendre",
      "Noms de domaine oubliés à racheter",
      "Produits en explosion",
      "Mots-clés rentables",
      "Niches sans concurrence",
    ],
    featured: true,
  },
  {
    slug: "clone-anything-ai",
    name: "Clone Anything AI",
    tagline: "Reconstruisez n'importe quelle app, à votre façon",
    description:
      "À partir d'une application ou d'un site public, génère une architecture similaire (sans copier le code propriétaire), accompagnée d'un design moderne et d'une feuille de route de développement prête à l'emploi.",
    category: "Intelligence",
    icon: "🧬",
    monthlyPrice: 119,
    features: [
      "Analyse d'apps & sites publics",
      "Architecture technique générée",
      "Design moderne proposé",
      "Feuille de route de développement",
      "Choix de la stack technique",
      "Respect du code propriétaire (aucune copie)",
    ],
    featured: true,
  },
  {
    slug: "world-automation-os",
    name: "World Automation OS",
    tagline: "Le système d'exploitation de vos automatisations",
    description:
      "Connecte des centaines de services et automatise vos tâches répétitives grâce à des agents IA. Décrivez le résultat voulu, les agents orchestrent les outils et exécutent le travail à votre place.",
    category: "Intelligence",
    icon: "⚙️",
    monthlyPrice: 109,
    features: [
      "Connexion à des centaines de services",
      "Agents IA autonomes",
      "Automatisation des tâches répétitives",
      "Orchestration multi-outils",
      "Déclencheurs & scénarios",
      "Exécution surveillée en temps réel",
    ],
    featured: true,
  },
  {
    slug: "global-video-factory",
    name: "Global Video Factory",
    tagline: "Une vidéo, tous les formats, toutes les langues",
    description:
      "Importez une seule vidéo : elle est automatiquement déclinée en versions adaptées à TikTok, Instagram, YouTube, Facebook, LinkedIn et X, puis traduite en plusieurs langues avec doublage et sous-titres.",
    category: "Vidéo",
    icon: "🎬",
    monthlyPrice: 89,
    features: [
      "Reformatage automatique (TikTok, Instagram, YouTube, Facebook, LinkedIn, X)",
      "Versions multilingues",
      "Doublage automatique",
      "Sous-titres générés",
      "Recadrage intelligent par plateforme",
      "Publication programmée",
    ],
    featured: true,
  },
  {
    slug: "future-trends-engine",
    name: "Future Trends Engine",
    tagline: "Repérez les secteurs en croissance avant tout le monde",
    description:
      "Analyse les brevets, les publications scientifiques, les offres d'emploi et les investissements pour détecter les secteurs en croissance avant qu'ils ne deviennent populaires. Suit aussi les tendances aux États-Unis et vous livre un rapport chaque jour.",
    category: "Intelligence",
    icon: "🔮",
    monthlyPrice: 139,
    features: [
      "Analyse des brevets",
      "Publications scientifiques",
      "Offres d'emploi & investissements",
      "Détection précoce des secteurs en croissance",
      "Tendances USA suivies en continu",
      "Rapport quotidien automatique",
    ],
    featured: true,
  },
  {
    slug: "ai-acquisition-finder",
    name: "AI Acquisition Finder",
    tagline: "Dénichez la prochaine pépite à racheter",
    description:
      "Trouve des entreprises SaaS sous-évaluées ou des projets à reprendre, estime leur potentiel de croissance et vous aide à préparer une acquisition de A à Z.",
    category: "Intelligence",
    icon: "🤝",
    monthlyPrice: 149,
    features: [
      "Détection de SaaS sous-évalués",
      "Projets à reprendre",
      "Estimation du potentiel de croissance",
      "Évaluation & valorisation",
      "Préparation du dossier d'acquisition",
      "Analyse des risques",
    ],
    featured: true,
  },
  {
    slug: "personal-ai-workforce",
    name: "Personal AI Workforce",
    tagline: "Votre équipe d'agents IA qui travaille pour vous",
    description:
      "Disposez de plusieurs agents IA spécialisés — marketing, ventes, finance, juridique, développement et recherche — qui collaborent entre eux pour exécuter vos projets de bout en bout, comme une véritable équipe.",
    category: "Intelligence",
    icon: "👥",
    monthlyPrice: 159,
    features: [
      "Agent Marketing",
      "Agent Ventes",
      "Agent Finance",
      "Agent Juridique",
      "Agent Développement",
      "Agent Recherche",
      "Collaboration inter-agents",
    ],
    featured: true,
  },
  {
    slug: "ai-investment-radar",
    name: "AI Investment Radar",
    tagline: "La recherche de marché, augmentée par l'IA",
    description:
      "Analyse les marchés, les startups et les tendances économiques pour fournir des informations de recherche claires et synthétiques. Outil d'aide à la recherche uniquement : aucune promesse de gains ni conseil en investissement.",
    category: "Intelligence",
    icon: "📡",
    monthlyPrice: 129,
    features: [
      "Analyse des marchés",
      "Veille sur les startups",
      "Suivi des tendances économiques",
      "Synthèses de recherche",
      "Tableaux de bord personnalisables",
      "Informations à but de recherche uniquement",
    ],
    featured: true,
  },
  {
    slug: "universal-knowledge-engine",
    name: "Universal Knowledge Engine",
    tagline: "Toute la connaissance, vérifiée et sourcée",
    description:
      "Recherche dans des milliers de sources, compare les informations entre elles et produit des rapports structurés accompagnés de leurs références, pour des réponses fiables et vérifiables.",
    category: "Intelligence",
    icon: "📚",
    monthlyPrice: 119,
    features: [
      "Recherche dans des milliers de sources",
      "Comparaison croisée des informations",
      "Rapports structurés",
      "Références & citations",
      "Détection des contradictions",
      "Export PDF & partage",
    ],
    featured: true,
  },
  {
    slug: "ai-os-smartphones",
    name: "AI OS for Smartphones",
    tagline: "L'IA qui pilote votre téléphone à votre place",
    description:
      "Une surcouche pour smartphone qui orchestre plusieurs IA pour vous assister dans vos tâches quotidiennes : messages, agenda, achats, déplacements et applications, le tout coordonné par un assistant unique.",
    category: "Intelligence",
    icon: "📱",
    monthlyPrice: 79,
    features: [
      "Surcouche multi-IA",
      "Orchestration des applications",
      "Assistance aux tâches quotidiennes",
      "Commandes en langage naturel",
      "Automatisations contextuelles",
      "Compatible iOS & Android",
    ],
    featured: true,
  },
  {
    slug: "regsentry",
    name: "RegSentry",
    tagline: "La conformité réglementaire en pilote automatique",
    description:
      "RegTech par IA pour les secteurs réglementés (santé/HIPAA, SOC 2, CMMC, CSRD). Automatise les revues de conformité, la collecte de preuves et les audits. L'une des niches SaaS US les plus rentables : la demande est « obligée » par la loi (ex. conformité dentaire à 300–500 $/cabinet/mois, 85 % de marge).",
    category: "Conformité",
    icon: "✅",
    monthlyPrice: 249,
    features: [
      "Revues de conformité automatisées (HIPAA, SOC 2, CMMC, CSRD)",
      "Collecte de preuves & pistes d'audit",
      "Modèles de politiques par secteur",
      "Alertes de changement réglementaire",
      "Tableau de bord de conformité",
      "Rapports prêts pour l'auditeur",
    ],
    featured: true,
  },
  {
    slug: "verticalcrm",
    name: "VerticalCRM",
    tagline: "Le CRM taillé pour votre métier",
    description:
      "CRM vertical pensé pour un secteur précis — immobilier, fitness, vétérinaires, assurance, recrutement — avec des workflows métier prêts à l'emploi. Les CRM de niche surpassent les CRM génériques et atteignent souvent 10 000 $+ de MRR en 12 mois.",
    category: "Ventes",
    icon: "🏷️",
    monthlyPrice: 79,
    features: [
      "Workflows spécifiques au métier",
      "Pipeline & relances automatiques",
      "Modèles sectoriels prêts à l'emploi",
      "Automatisations marketing intégrées",
      "Application mobile",
      "Intégrations sectorielles",
    ],
    featured: true,
  },
  {
    slug: "repurposeflow",
    name: "RepurposeFlow",
    tagline: "Un contenu, décliné partout automatiquement",
    description:
      "Repurposing de contenu par IA — la niche micro-SaaS n°1 de 2026. Transformez un podcast, une vidéo ou un article en dizaines de formats prêts à publier : posts sociaux, newsletters, threads, extraits courts et résumés.",
    category: "Marketing",
    icon: "♻️",
    monthlyPrice: 39,
    features: [
      "1 source → des dizaines de formats",
      "Posts pour chaque réseau social",
      "Newsletters & threads générés",
      "Extraits courts (clips & citations)",
      "Adaptation au ton de la marque",
      "Programmation de publication",
    ],
    featured: true,
  },
  {
    slug: "silkroute",
    name: "SilkRoute",
    tagline: "Le meilleur prix depuis la Chine, livré chez vous",
    description:
      "Montrez un produit ou collez un lien : SilkRoute cherche le meilleur prix sur les grands sites chinois (Taobao, 1688, Pinduoduo, AliExpress, Alibaba, DHgate, Temu, Banggood…), compare la qualité, puis passe par un agent d'achat (Superbuy, CSSBuy) pour consolider et expédier jusqu'en Suède. Mode Pro inclus : les techniques que les grands vendeurs américains gardent secrètes — remonter à l'usine d'origine via les registres de douane, trouver le prix usine par image inversée, et les plateformes B2B.",
    category: "E-commerce",
    icon: "🐉",
    monthlyPrice: 49,
    features: [
      "Recherche du meilleur prix à partir d'un lien ou d'une photo",
      "Marketplaces : Taobao, 1688, Pinduoduo, AliExpress, Alibaba, DHgate, Temu, Banggood",
      "Agents d'achat & réexpédition : Superbuy, CSSBuy",
      "Filtre qualité : avis, notes et vendeurs vérifiés",
      "Calcul des frais de port, délais, douane & TVA vers la Suède",
      "Consolidation de colis (un seul envoi)",
      "Détection des contrefaçons (achat de confiance)",
      "🔓 Mode Pro — remonter à l'usine via les registres d'import (ImportYeti, Panjiva)",
      "🔓 Mode Pro — prix usine par recherche d'image inversée (1688, AliPrice)",
      "🔓 Mode Pro — plateformes B2B : Global Sources, Made-in-China, Yiwugo",
      "🔓 Mode Pro — fulfillment dropshipping : CJ Dropshipping, DSers",
      "🔓 Mode Pro — recherche produit & prix : Keepa, Jungle Scout, Helium 10",
    ],
    featured: true,
  },
  {
    slug: "flowcrm",
    name: "FlowCRM",
    tagline: "Pipeline de ventes sans friction",
    description:
      "Gérez prospects, contacts et opportunités dans un pipeline visuel. Automatisez les relances et suivez chaque deal jusqu'à la signature.",
    category: "Ventes",
    icon: "📈",
    monthlyPrice: 29,
    features: ["Pipeline glisser-déposer", "Relances automatiques", "Rapports de ventes", "Intégration e-mail"],
  },
  {
    slug: "pulse-analytics",
    name: "Pulse Analytics",
    tagline: "Vos métriques en temps réel",
    description:
      "Tableaux de bord temps réel pour suivre trafic, conversions et rétention. Connectez vos sources de données en quelques clics.",
    category: "Analytique",
    icon: "📊",
    monthlyPrice: 49,
    features: ["Tableaux de bord temps réel", "Entonnoirs de conversion", "Alertes intelligentes", "Export CSV/API"],
  },
  {
    slug: "deskly",
    name: "Deskly",
    tagline: "Support client centralisé",
    description:
      "Centralisez tickets, e-mails et chat dans une seule boîte de réception partagée. Répondez plus vite avec des modèles et l'IA.",
    category: "Support",
    icon: "🎧",
    monthlyPrice: 25,
    features: ["Boîte partagée", "Réponses suggérées par IA", "Base de connaissances", "SLA & priorités"],
  },
  {
    slug: "billwise",
    name: "BillWise",
    tagline: "Facturation et abonnements",
    description:
      "Automatisez la facturation récurrente, gérez les abonnements et relancez les paiements échoués sans effort.",
    category: "Finance",
    icon: "💳",
    monthlyPrice: 39,
    features: ["Facturation récurrente", "Relance des impayés", "Multi-devises", "Conformité TVA"],
  },
  {
    slug: "teamsync",
    name: "TeamSync",
    tagline: "Collaboration d'équipe",
    description:
      "Messagerie, canaux et appels vidéo réunis pour garder votre équipe alignée où qu'elle soit.",
    category: "Productivité",
    icon: "💬",
    monthlyPrice: 19,
    features: ["Canaux & messages", "Appels vidéo HD", "Partage de fichiers", "Fil de discussions"],
  },
  {
    slug: "deploybot",
    name: "DeployBot",
    tagline: "Déploiement continu simplifié",
    description:
      "Déployez vos applications en un clic avec des pipelines CI/CD préconfigurés et des retours arrière instantanés.",
    category: "Développement",
    icon: "🚀",
    monthlyPrice: 59,
    features: ["Pipelines CI/CD", "Retour arrière en 1 clic", "Environnements de préversion", "Journaux en direct"],
  },
  {
    slug: "mailforge",
    name: "MailForge",
    tagline: "Campagnes e-mail performantes",
    description:
      "Créez, envoyez et mesurez des campagnes e-mail avec un éditeur visuel et l'automatisation par scénarios.",
    category: "Marketing",
    icon: "✉️",
    monthlyPrice: 35,
    features: ["Éditeur glisser-déposer", "Scénarios d'automatisation", "Tests A/B", "Segmentation avancée"],
  },
  {
    slug: "taskhive",
    name: "TaskHive",
    tagline: "Gestion de projets agile",
    description:
      "Planifiez, suivez et livrez vos projets avec des tableaux Kanban, des sprints et des diagrammes de Gantt.",
    category: "Productivité",
    icon: "🗂️",
    monthlyPrice: 22,
    features: ["Tableaux Kanban", "Sprints & backlog", "Diagramme de Gantt", "Suivi du temps"],
  },
  {
    slug: "securevault",
    name: "SecureVault",
    tagline: "Gestion des mots de passe d'équipe",
    description:
      "Stockez et partagez vos identifiants en toute sécurité avec un chiffrement de bout en bout et des contrôles d'accès.",
    category: "Sécurité",
    icon: "🔐",
    monthlyPrice: 15,
    features: ["Chiffrement bout en bout", "Partage sécurisé", "Audit d'accès", "Authentification 2FA"],
  },
  {
    slug: "shipfast",
    name: "ShipFast",
    tagline: "Logistique e-commerce",
    description:
      "Synchronisez vos commandes, imprimez vos étiquettes et suivez chaque colis depuis un tableau de bord unique.",
    category: "E-commerce",
    icon: "📦",
    monthlyPrice: 45,
    features: ["Étiquettes d'expédition", "Suivi multi-transporteurs", "Gestion des retours", "Synchro boutiques"],
  },
  {
    slug: "insightdb",
    name: "InsightDB",
    tagline: "Base de données managée",
    description:
      "Base de données PostgreSQL managée avec sauvegardes automatiques, mise à l'échelle et haute disponibilité.",
    category: "Développement",
    icon: "🗄️",
    monthlyPrice: 69,
    features: ["Sauvegardes automatiques", "Mise à l'échelle auto", "Réplicas en lecture", "Surveillance 24/7"],
  },
  {
    slug: "brandkit",
    name: "BrandKit",
    tagline: "Gestion d'identité de marque",
    description:
      "Centralisez logos, couleurs et chartes graphiques pour garder une marque cohérente sur tous vos supports.",
    category: "Design",
    icon: "🎨",
    monthlyPrice: 18,
    features: ["Bibliothèque d'actifs", "Chartes partagées", "Versionnage", "Accès invités"],
  },
  {
    slug: "callcenter-pro",
    name: "CallCenter Pro",
    tagline: "Téléphonie cloud",
    description:
      "Standard téléphonique cloud avec routage intelligent, enregistrement des appels et statistiques détaillées.",
    category: "Support",
    icon: "📞",
    monthlyPrice: 42,
    features: ["Routage intelligent", "Enregistrement d'appels", "Numéros internationaux", "Statistiques d'appels"],
  },
  {
    slug: "docuflow",
    name: "DocuFlow",
    tagline: "Signature électronique",
    description:
      "Envoyez, signez et archivez vos documents légalement avec une signature électronique conforme.",
    category: "Finance",
    icon: "✍️",
    monthlyPrice: 27,
    features: ["Signature conforme eIDAS", "Modèles réutilisables", "Suivi en temps réel", "Archivage sécurisé"],
  },
  {
    slug: "stockpilot",
    name: "StockPilot",
    tagline: "Gestion des stocks",
    description:
      "Suivez vos stocks en temps réel, anticipez les ruptures et automatisez vos commandes fournisseurs.",
    category: "E-commerce",
    icon: "📋",
    monthlyPrice: 38,
    features: ["Stock temps réel", "Alertes de rupture", "Commandes auto", "Multi-entrepôts"],
  },
  {
    slug: "feedbackloop",
    name: "FeedbackLoop",
    tagline: "Enquêtes et sondages",
    description:
      "Recueillez l'avis de vos clients avec des enquêtes ciblées, des NPS et des analyses de sentiment.",
    category: "Marketing",
    icon: "⭐",
    monthlyPrice: 21,
    features: ["Enquêtes NPS", "Sondages intégrés", "Analyse de sentiment", "Rapports partageables"],
  },
  {
    slug: "codereview-ai",
    name: "CodeReview AI",
    tagline: "Revue de code assistée par IA",
    description:
      "Détectez bugs et failles de sécurité avant la fusion grâce à des revues de code automatisées par IA.",
    category: "Développement",
    icon: "🤖",
    monthlyPrice: 55,
    features: ["Analyse de PR", "Détection de failles", "Suggestions de refactor", "Intégration Git"],
  },
  {
    slug: "timekeeper",
    name: "TimeKeeper",
    tagline: "Suivi du temps et paie",
    description:
      "Pointage, feuilles de temps et calcul de paie réunis pour simplifier la gestion de vos équipes.",
    category: "RH",
    icon: "⏱️",
    monthlyPrice: 16,
    features: ["Pointage mobile", "Feuilles de temps", "Calcul de paie", "Gestion des congés"],
  },
  {
    slug: "hireflow",
    name: "HireFlow",
    tagline: "Recrutement simplifié",
    description:
      "Gérez vos offres, candidatures et entretiens dans un pipeline de recrutement collaboratif.",
    category: "RH",
    icon: "🧑‍💼",
    monthlyPrice: 33,
    features: ["Pipeline de candidats", "Pages carrière", "Planification d'entretiens", "Notes collaboratives"],
  },
  {
    slug: "cloudstore",
    name: "CloudStore",
    tagline: "Stockage de fichiers sécurisé",
    description:
      "Stockez, synchronisez et partagez vos fichiers d'entreprise avec un contrôle d'accès granulaire.",
    category: "Productivité",
    icon: "☁️",
    monthlyPrice: 12,
    features: ["Synchro multi-appareils", "Partage par lien", "Contrôle d'accès", "Historique des versions"],
  },
  {
    slug: "adboost",
    name: "AdBoost",
    tagline: "Gestion de campagnes publicitaires",
    description:
      "Pilotez vos campagnes Google, Meta et LinkedIn depuis une interface unique avec optimisation automatique.",
    category: "Marketing",
    icon: "🎯",
    monthlyPrice: 64,
    features: ["Multi-plateformes", "Optimisation auto", "Rapports unifiés", "Suivi des conversions"],
  },
  {
    slug: "bookme",
    name: "BookMe",
    tagline: "Prise de rendez-vous en ligne",
    description:
      "Laissez vos clients réserver en ligne avec synchronisation de calendrier et rappels automatiques.",
    category: "Productivité",
    icon: "📅",
    monthlyPrice: 14,
    features: ["Page de réservation", "Synchro calendrier", "Rappels SMS/e-mail", "Paiements en ligne"],
  },
  {
    slug: "sentryguard",
    name: "SentryGuard",
    tagline: "Surveillance et alertes",
    description:
      "Surveillez la disponibilité et les performances de vos services avec des alertes en temps réel.",
    category: "Sécurité",
    icon: "🛡️",
    monthlyPrice: 31,
    features: ["Surveillance uptime", "Alertes multicanal", "Pages de statut", "Historique d'incidents"],
  },
  {
    slug: "learnhub",
    name: "LearnHub",
    tagline: "Plateforme de formation",
    description:
      "Créez et diffusez des formations en ligne avec suivi de progression et certificats automatiques.",
    category: "RH",
    icon: "🎓",
    monthlyPrice: 28,
    features: ["Création de cours", "Suivi de progression", "Quiz & certificats", "Espace apprenant"],
  },
  {
    slug: "chatwidget",
    name: "ChatWidget",
    tagline: "Chat en direct pour sites web",
    description:
      "Ajoutez un chat en direct à votre site et convertissez vos visiteurs avec des réponses instantanées.",
    category: "Support",
    icon: "🗨️",
    monthlyPrice: 17,
    features: ["Widget personnalisable", "Chatbot IA", "Déclencheurs automatiques", "Historique de conversations"],
  },
  {
    slug: "expensly",
    name: "Expensly",
    tagline: "Gestion des notes de frais",
    description:
      "Numérisez vos reçus, automatisez les validations et remboursez vos équipes plus vite.",
    category: "Finance",
    icon: "🧾",
    monthlyPrice: 20,
    features: ["Scan de reçus", "Flux d'approbation", "Cartes virtuelles", "Export comptable"],
  },
  {
    slug: "socialpilot",
    name: "SocialPilot",
    tagline: "Gestion des réseaux sociaux",
    description:
      "Planifiez, publiez et analysez vos publications sur tous vos réseaux depuis un calendrier unique.",
    category: "Marketing",
    icon: "📱",
    monthlyPrice: 26,
    features: ["Calendrier de publication", "File d'attente automatique", "Analytique sociale", "Gestion multi-comptes"],
  },
  {
    slug: "formcraft",
    name: "FormCraft",
    tagline: "Formulaires et collecte de données",
    description:
      "Construisez des formulaires intelligents avec logique conditionnelle et intégrations en quelques minutes.",
    category: "Productivité",
    icon: "📝",
    monthlyPrice: 13,
    features: ["Éditeur visuel", "Logique conditionnelle", "Intégrations Zapier", "Notifications instantanées"],
  },
  {
    slug: "datapipe",
    name: "DataPipe",
    tagline: "ETL et intégration de données",
    description:
      "Connectez vos sources de données et automatisez vos flux ETL vers votre entrepôt en toute fiabilité.",
    category: "Analytique",
    icon: "🔗",
    monthlyPrice: 72,
    features: ["200+ connecteurs", "Synchro planifiée", "Transformations SQL", "Surveillance des flux"],
  },
  {
    slug: "voicescribe",
    name: "VoiceScribe",
    tagline: "Transcription et notes de réunion",
    description:
      "Transcrivez automatiquement vos réunions, générez des résumés et partagez les actions à mener.",
    category: "Productivité",
    icon: "🎙️",
    monthlyPrice: 24,
    features: ["Transcription IA", "Résumés automatiques", "Détection des actions", "Recherche dans l'audio"],
  },
  {
    slug: "streamcast-tv",
    name: "StreamCast TV",
    tagline: "Lancez votre chaîne IPTV/OTT légale en quelques minutes",
    description:
      "Plateforme IPTV/OTT clé en main pour diffuser votre propre contenu ou du contenu dont vous détenez les droits : chaînes d'entreprise, hôtels, écoles, télés locales ou créateurs. Gestion des abonnements, des droits et de la diffusion multi-écrans, dans le respect de la législation.",
    category: "Vidéo",
    icon: "📺",
    monthlyPrice: 79,
    features: [
      "Diffusion de votre contenu sous licence",
      "Applications multi-écrans (TV, mobile, web)",
      "Gestion des abonnements & paiements",
      "Protection des contenus (DRM)",
      "Gestion des droits & géo-restrictions",
      "Statistiques d'audience",
    ],
  },
  {
    slug: "streamcast-server",
    name: "StreamCast Server",
    tagline: "Votre serveur de streaming IPTV/OTT managé",
    description:
      "Serveur de streaming managé pour diffuser votre propre contenu ou du contenu sous licence : ingestion des sources, transcodage automatique, sortie HLS/DASH, protection DRM et architecture distribuée. Relais, CDN et serveurs multi-régions limitent la charge et les coupures — pour diffuser votre origine autorisée à grande échelle.",
    category: "Vidéo",
    icon: "🖥️",
    monthlyPrice: 99,
    features: [
      "Ingestion RTMP/SRT",
      "Transcodage adaptatif (multi-qualités)",
      "Sortie HLS & DASH",
      "Serveurs relais & reverse proxy (depuis votre origine)",
      "Réseau de diffusion (CDN) intégré",
      "Serveurs multi-régions & haute disponibilité",
      "Protection DRM & jetons d'accès",
      "Génération de playlists M3U/M3U8",
      "Statistiques de diffusion",
    ],
    featured: true,
  },
  // --- Bientôt disponibles (affichés en grisé) ---
  {
    slug: "ai-legal-guardian",
    name: "AI Legal Guardian",
    tagline: "Vos contrats et votre conformité sous surveillance",
    description:
      "Analyse vos contrats, détecte les clauses à risque et surveille en continu votre conformité réglementaire pour vous alerter avant le moindre problème.",
    category: "Juridique",
    icon: "⚖️",
    monthlyPrice: 89,
    features: [
      "Analyse de contrats",
      "Détection de clauses à risque",
      "Veille réglementaire",
      "Alertes de conformité",
      "Modèles juridiques",
    ],
    featured: true,
    comingSoon: true,
  },
  {
    slug: "ai-content-empire",
    name: "AI Content Empire",
    tagline: "Une machine à contenu SEO qui ne dort jamais",
    description:
      "Produit articles, pages et publications optimisés pour le référencement à grande échelle, en respectant votre ligne éditoriale et votre stratégie de mots-clés.",
    category: "Marketing",
    icon: "📰",
    monthlyPrice: 79,
    features: [
      "Génération d'articles SEO",
      "Stratégie de mots-clés",
      "Calendrier éditorial",
      "Publication multi-sites",
      "Optimisation continue",
    ],
    featured: true,
    comingSoon: true,
  },
  {
    slug: "ai-customer-magnet",
    name: "AI Customer Magnet",
    tagline: "Attirez et qualifiez vos clients automatiquement",
    description:
      "Identifie vos clients idéaux, génère des prospects qualifiés et engage la conversation à votre place pour remplir votre pipeline en continu.",
    category: "Ventes",
    icon: "🧲",
    monthlyPrice: 99,
    features: [
      "Identification de clients idéaux",
      "Génération de prospects",
      "Qualification automatique",
      "Prise de contact personnalisée",
      "Synchronisation CRM",
    ],
    featured: true,
    comingSoon: true,
  },
  {
    slug: "ai-market-expander",
    name: "AI Market Expander",
    tagline: "Lancez-vous sur de nouveaux marchés en un clic",
    description:
      "Analyse de nouveaux marchés, traduit et adapte votre offre culturellement, et bâtit un plan d'entrée local pour accélérer votre expansion internationale.",
    category: "Intelligence",
    icon: "🌍",
    monthlyPrice: 129,
    features: [
      "Analyse de marchés cibles",
      "Localisation & traduction",
      "Adaptation culturelle",
      "Plan d'entrée sur le marché",
      "Étude de la concurrence locale",
    ],
    featured: true,
    comingSoon: true,
  },
  {
    slug: "ai-competitor-tracker",
    name: "AI Competitor Tracker",
    tagline: "Gardez toujours une longueur d'avance",
    description:
      "Surveille en temps réel les prix, les fonctionnalités, les campagnes et les recrutements de vos concurrents, et vous alerte au moindre mouvement stratégique.",
    category: "Intelligence",
    icon: "🛰️",
    monthlyPrice: 109,
    features: [
      "Surveillance des prix",
      "Suivi des fonctionnalités",
      "Veille publicitaire",
      "Suivi des recrutements",
      "Alertes de mouvements stratégiques",
    ],
    featured: true,
    comingSoon: true,
  },
];

export const categories: string[] = Array.from(
  new Set(products.map((p) => p.category)),
).sort();

export function getProduct(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}
